const BOOKING_STATES = {
    INITIATED: "INITIATED",
    ONGOING: "ONGOING",
    COMPLETED: "COMPLETED",
    CANCELLED: "CANCELLED"
}

const NEGOTIATION_STATES = {
    NOPE: "NOPE",
    START: "START",
    SLOT_KNOWN: "SLOT_KNOWN",
    SIZE_OF_BOOKING_KNOWN: "BOOKING_SIZE_KNOWN",
    OFFER1_GIVEN: "OFFER1_GIVEN",
    OFFER2_GIVEN: "OFFER2_GIVEN",
    OFFER3_GIVEN: "OFFER3_GIVEN",
    ACCEPTED: "ACCEPTED",
}

const CLIENT_STATES = {
    ARRIVED: "ARRIVED",
    OPTIONS_GIVEN: "OPTIONS_GIVEN",
    NEGOTIATING: "NEGOTIATING",
    STARTED_BOOKING: "STARTED_BOOKING",
    COMPLETED_BOOKING: "COMPLETED_BOOKING",
    ORDERING: "ORDERING",
    COMPLETED: "COMPLETED",
}

export default {BOOKING_STATES, NEGOTIATION_STATES, CLIENT_STATES};
